// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxiWRkdxF_BXsuI8mwpdJUQqLv9eqjwW0',
    appId: '1:749174309531:web:d4e156512ccf28648afc3e',
    messagingSenderId: '749174309531',
    projectId: 'cvaapplication',
    authDomain: 'cvaapplication.firebaseapp.com',
    storageBucket: 'cvaapplication.appspot.com',
    measurementId: 'G-LRT8MJDP3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSaanIXum6svMEb7iBbss6JQqVHuqVPOw',
    appId: '1:749174309531:android:80175aeb5a63db408afc3e',
    messagingSenderId: '749174309531',
    projectId: 'cvaapplication',
    storageBucket: 'cvaapplication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABbZRVuuKJsIqNG9H0QXkXtxkTsUraVGs',
    appId: '1:749174309531:ios:b1e72bb376a403db8afc3e',
    messagingSenderId: '749174309531',
    projectId: 'cvaapplication',
    storageBucket: 'cvaapplication.appspot.com',
    iosClientId: '749174309531-01lqjjnrgnbdrk8k4jnqntuiomqh3pfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABbZRVuuKJsIqNG9H0QXkXtxkTsUraVGs',
    appId: '1:749174309531:ios:b1e72bb376a403db8afc3e',
    messagingSenderId: '749174309531',
    projectId: 'cvaapplication',
    storageBucket: 'cvaapplication.appspot.com',
    iosClientId: '749174309531-01lqjjnrgnbdrk8k4jnqntuiomqh3pfj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cvaApp',
  );
}
